const inputs = [
  {
    type: "text",
    name: "name",
    id: "name",
    label: "Name",
    required: true,
    error: false,
    helperText: "Is required",
  },
  {
    type: "text",
    name: "lastName",
    id: "lastName",
    label: "Last Name",
    required: true,
    error: false,
    helperText: "Is required",
  },
  {
    type: "number",
    name: "age",
    id: "age",
    label: "Age",
    required: true,
    error: false,
    helperText: "Is required",
  },
  {
    type: "email",
    name: "email",
    id: "email",
    label: "Email",
    required: true,
    error: false,
    helperText: "Must be a valid email",
  },
  {
    type: "text",
    name: "address",
    id: "address",
    label: "Address",
    required: true,
    error: false,
    helperText: "Is required",
  },
  {
    type: "tel",
    name: "phone",
    id: "phone",
    label: "Phone",
    required: false,
    error: false,
    helperText: "Must be a valid phone number",
    pattern: "^[0-9]{10}$",
  },
  {
    type: "switch",
    name: "delivered",
    id: "delivered",
    label: "Delivered",
  },
  {
    type: "textarea",
    name: "observations",
    id: "observations",
    label: "Observations",
    required: false,
  },
];

export default inputs;
